added design for wine title
microservices-course-itmo/frontend pull request #11
Opened 2020-09-29 00:19 UTC by izukovdariy

2020-09-29 12:25 UTC, gohabereg requested changes

2020-09-29 12:25 UTC, gohabereg commented on src/App.tsx
> +        <Tab.Screen name='WineCard' component={WineCardScreen} />
Это стоит убрать, так как карточка будет использоваться внутри экрана, а не как экран

2020-09-29 12:25 UTC, gohabereg commented on src/atoms/wineTitle/index.tsx
> +export interface IWine {
Если имя интерфейса не совпадает с именем какого-нибудь класса, лучше не добавлять `I` префикс

2020-09-29 12:25 UTC, gohabereg commented on src/atoms/wineTitle/index.tsx
> +export interface IWine {
```suggestion
export interface Wine {
```

2020-09-29 12:25 UTC, gohabereg commented on src/atoms/wineTitle/index.tsx
> +interface IWineResponse {
Аналогично
```suggestion
interface WineResponse {
```

2020-09-29 12:25 UTC, gohabereg commented on src/atoms/wineTitle/index.tsx
> +  })
Круто, что ты сразу подумала о запросе к API, но давай это все вынесем в папку API.
Пока не очень понятно как архитектурно мы будем его использовать

2020-09-29 12:25 UTC, gohabereg commented on src/atoms/wineTitle/index.tsx
> +const WineCard: React.FC<IWine> = () => {
Компонент вроде называется `WineCard`, а папка `wineTitle`. Надо, чтобы одинаково.

И если это все же карточка, то лучше переместить в папку `organisms`

2020-09-29 12:25 UTC, gohabereg commented on src/atoms/wineTitle/index.tsx
> +  React.useEffect(() => {
Давай просто импортировать useEffect и использовать отдельно

```
import React, { useEffect } from 'react';

...

useEffect(...);
```

2020-09-29 12:25 UTC, gohabereg commented on src/atoms/wineTitle/index.tsx
> +    getWine()
Лучше переписать на async/await — так более читабельно

2020-09-29 12:25 UTC, gohabereg commented on src/atoms/wineTitle/index.tsx
> +    <article>
Не уверен, что article здесь использовать семантически верно, лучше просто div

2020-09-29 12:25 UTC, gohabereg commented on src/atoms/wineTitle/index.tsx
> +      <h1 style={{ margin: 0 }}>{wine?.name}</h1>
Тут лучше не первого уровня заголовок, а хотя бы второго или третьего

2020-09-29 12:25 UTC, gohabereg commented on src/atoms/wineTitle/index.tsx
> +  })
И на самом деле, в этом компоненте не стоит вызывать API, лучше просто принимать пропсы для названия, описания, цены.

2020-09-29 12:25 UTC, gohabereg commented on src/atoms/wineTitle/index.spec.tsx
> +  })
Можно добавить тесты на то, что
1. Рендерится объем, который передали в пропс
2. Рендерится описание, которое передали в пропс
3. Рендерится имя, которое передали в пропс
4. Если есть опциональные поля, то нужны тесты на то, что они не рендерятся, если не переданы

Выглядеть эти тесты должны примерно так

```
it('should render correct volume', () => {
  const volume = 0.75;

  const { getByText } = render(
    <WineCard
       volume={volume}
       description='Австралия, Красное, сухое'
       name='Canti Merlot'
    />
   )

   const volumeElement = getByText(volume)

  expect(volumeElement).toBeDefined()
})
```

2020-09-30 08:16 UTC, izukovdariy commented on src/atoms/wineTitle/index.spec.tsx
> +  })
Исправила код, почему-то новые тесты не проходит

2020-09-30 16:34 UTC, gohabereg requested changes
Я оставил suggestions, если перейти во вкладку `Files changed`, можно добавить каждый в suggestion bunch и закоммитить все прямо отсюда

2020-09-30 16:34 UTC, gohabereg commented on src/atoms/WineTitle/index.tsx
> +export interface Wine {
```suggestion
export interface WineTitleProps {
```

2020-09-30 16:34 UTC, gohabereg commented on src/atoms/WineTitle/index.tsx
> +function WineTitle({ name, description, volume }: Wine): ReactElement<Wine> {
```suggestion
function WineTitle({ name, description, volume }: WineTitleProps): ReactElement<Wine> {
```

2020-09-30 16:34 UTC, gohabereg commented on src/atoms/WineTitle/index.tsx
> +  price?: number
В этом компоненте цена вроде не нужна
```suggestion
```

2020-09-30 16:34 UTC, gohabereg commented on src/atoms/WineTitle/index.spec.tsx
> +})
describe описывает test-suite — набор тестов-кейсов. Поэтому не нужно на каждый кейс писать отдельный
```suggestion
describe('<WineTitle />', () => {
  it('should render correct volume', () => {
    const volume = 0.75
    const { getByText } = render(
      <WineTitle
        name='Canti Merlot'
        description='Австралия, Красное, сухое'
        volume={volume}
      />
    )
    const volumeElement = getByText(volume.toString())
   
    expect(volumeElement).toBeDefined()
  })

  it('should render correct description', () => {
    const description = 'Австралия, Красное, сухое'
    const { getByText } = render(
      <WineTitle name='Canti Merlot' description={description} volume={0.75} />
    )
    const descriptionElement = getByText(description)
    
    expect(descriptionElement).toBeDefined()
  })

  it('should render correct name', () => {
    const name = 'Canti Merlot'
    const { getByText } = render(
      <WineTitle
        name={name}
        description='Австралия, Красное, сухое'
        volume={0.75}
      />
    )
    const nameElement = getByText(name)
    
    expect(nameElement).toBeDefined()
  })
})
```

2020-09-30 18:12 UTC, gohabereg approved these changes

2020-09-30 18:12 UTC, gohabereg commented on src/atoms/WineTitle/index.tsx
> +const styles = StyleSheet.create({
Тут не критично, так как стилей не много, но лучше их переносить под компонент, чтобы в начале файла его было сразу видно

2020-10-01 16:39 UTC, Bukilan approved these changes

2020-10-01 16:40 UTC, merged