wine rating component
microservices-course-itmo/frontend pull request #14
Opened 2020-09-30 16:35 UTC by CleanBread

2020-09-30 16:58 UTC, gohabereg requested changes

2020-09-30 16:58 UTC, gohabereg commented on src/atoms/WineRating/index.tsx
> +              key={star}
star тут всегда будет 0, лучше index заюзать

2020-09-30 16:58 UTC, gohabereg commented on src/atoms/WineRating/index.tsx
> +const styles = StyleSheet.create({
Перемести плиз стили под компонент, чтобы при открытии файла его сразу было видно

2020-09-30 16:58 UTC, gohabereg commented on src/atoms/WineRating/index.tsx
> +  rating?: number | 0
А зачем `number | 0`?

2020-09-30 16:58 UTC, gohabereg commented on src/atoms/WineRating/index.tsx
> +  rating?: number | 0
И лучше сделать пропс обязательным, чтобы всегда передавались какие-то данные. И соответственно убрать дефолтное значение

2020-09-30 16:58 UTC, gohabereg commented on src/atoms/WineRating/index.spec.tsx
> +  it('should render', () => {
Я бы добавил тест на то, что количество отмеченных звезд равнялось числу, которое передали в пропс

2020-10-09 18:23 UTC, alexstrive commented
Жду изменений, которые @gohabereg  указал, и тогда готов ставить апрув.

2020-10-13 08:56 UTC, alexstrive commented
@CleanBread что по прогрессу?

2020-10-26 12:51 UTC, alexstrive commented
@CleanBread ожидаем статуса о PR

2020-10-26 15:37 UTC, gohabereg commented on src/atoms/WineRating/index.tsx
> +              key={star}
Не пофикшено

2020-10-29 18:07 UTC, gohabereg approved these changes

2020-10-29 18:10 UTC, merged