Borwi4ok
microservices-course-itmo/frontend pull request #15
Opened 2020-09-30 23:19 UTC by borwi4ok

some atoms

2020-10-01 09:20 UTC, gohabereg requested changes

2020-10-01 09:20 UTC, gohabereg commented on .gitignore
> +*.lock
lock не нужнр класть в игнор, там перечислены точные версии зависимостей проекта

2020-10-01 09:20 UTC, gohabereg commented on package.json
> +    "@testing-library/jest-dom": "^5.11.4",
Это не нужно вроде, можно удалить

2020-10-01 09:20 UTC, gohabereg commented on src/atoms/advice/index.spec.tsx
> +  expect(elem).toBeDefined()
```suggestion

  expect(elem).toBeDefined()
```

2020-10-01 09:20 UTC, gohabereg commented on src/atoms/advice/index.spec.tsx
> +  expect(element).toBeDefined()
```suggestion

  expect(element).toBeDefined()
```

2020-10-01 09:20 UTC, gohabereg commented on src/atoms/advice/index.spec.tsx
> +  expect(element).toBeDefined()
```suggestion

  expect(element).toBeDefined()
```

2020-10-01 09:20 UTC, gohabereg commented on src/atoms/advice/index.spec.tsx
> +  expect(elem).toBeDefined()
Тут лучше передать валидные данные и поиск делать не обязательно, если при рендере будет ошибка тест и так упадет

2020-10-01 09:20 UTC, gohabereg commented on src/atoms/advice/index.spec.tsx
> +})
Не хватает кейса для валидных данных и проверки, что они отрендерились)

2020-10-01 09:20 UTC, gohabereg commented on src/atoms/advice/index.tsx
> +  if (ratioAdvice < 0) ratio = 0
```suggestion
  const ratio = Math.min(Math.max(0, ratioAdvice), 100)
```

2020-10-01 09:20 UTC, gohabereg commented on src/atoms/advice/index.tsx
> +        {ratio}%
Возможно, тесты падают из-за того, что тут перенос строки

2020-10-01 09:21 UTC, gohabereg commented
Используй плиз yarn, а package-lock.json удали

2020-10-01 10:57 UTC, borwi4ok commented on src/atoms/advice/index.spec.tsx
> +  expect(elem).toBeDefined()
отступ сделать?

2020-10-01 11:00 UTC, borwi4ok commented on src/atoms/advice/index.tsx
> +        {ratio}%
они ещё падают из-за того,что styles используются до объявления

2020-10-01 11:03 UTC, borwi4ok commented on src/atoms/advice/index.tsx
> +  if (ratioAdvice < 0) ratio = 0
Мне кажется это менее читаемо,что думаешь?

2020-10-01 14:21 UTC, gohabereg commented on src/atoms/advice/index.spec.tsx
> +  expect(elem).toBeDefined()
Да, после объявления переменных стоит делать отступ. Я чуть позже настрою линтер, чтобы это автоматом происходило

2020-10-01 14:22 UTC, gohabereg commented on src/atoms/advice/index.tsx
> +        {ratio}%
Это пофиксили в другом ПР, надуюсь в ближайшее время его закроют

2020-10-01 17:14 UTC, gohabereg approved these changes, later dismissed

2020-10-01 17:14 UTC, gohabereg commented on src/atoms/advice/index.tsx
> +function rightBordersHandler(value: number): number {
Функцию лучше перенести под компонент

2020-10-01 20:00 UTC, gohabereg approved these changes

2020-10-02 10:19 UTC, gohabereg commented
Публикация не проходит, потому что ПР их форка. Это ок, но в следующий раз лучше пушить прямо сюда, у тебя есть доступ

2020-10-09 18:20 UTC, alexstrive commented on src/atoms/advice/index.tsx
> +      <Text>{displayData}</Text>
Почему бы сразу не отображать текст в данном месте со значением вычисленной переменной?

То есть
```
<Text>Подходит вам...</Text>
```

2020-10-13 08:56 UTC, alexstrive commented
Дубликат https://github.com/microservices-course-itmo/wineup-expo/pull/20

2020-10-13 08:56 UTC, closed without merging