Wine shop name component
microservices-course-itmo/frontend pull request #18
Opened 2020-10-05 06:40 UTC by ld50eli

2020-10-05 08:07 UTC, gohabereg requested changes
В следующий раз лучше сразу в репозиторий пушить, а не через форк

2020-10-05 08:07 UTC, gohabereg commented on src/atoms/WineShopName/index.spec.tsx
> +import WineShopName from '../../atoms/WineShopName'
```suggestion
import WineShopName from './index'
```

2020-10-05 08:07 UTC, gohabereg commented on src/atoms/WineShopName/index.tsx
> +const WineShopName = ({ image = logo, name, description }: ComponentProps) => {
Значение по умолчанию стоит убрать

2020-10-05 08:07 UTC, gohabereg commented on src/atoms/WineShopName/style.tsx
> +export default StyleSheet.create({
У нас везде оставляют стили в одном файле с компонентом, лучше придерживаться этого

2020-10-07 17:09 UTC, gohabereg approved these changes

2020-10-09 18:10 UTC, alexstrive commented on src/atoms/WineShopName/index.tsx
> +const styles = StyleSheet.create({
Как мне помнится, @gohabereg и @Bukilan договаривались вначале отображать код компонента, а стили - после.

2020-10-10 08:29 UTC, alexstrive approved these changes

2020-10-10 08:30 UTC, alexstrive approved these changes

2020-10-12 06:05 UTC, Bukilan approved these changes

2020-10-13 08:57 UTC, alexstrive commented
@gohabereg ожидаем твоего обзора.

2020-10-13 14:01 UTC, gohabereg approved these changes

2020-10-13 20:31 UTC, merged