Authentication validation features
microservices-course-itmo/frontend pull request #19
Opened 2020-10-10 21:26 UTC by devchep

1) Для инпутов эмейла и пароля накручены проверки и сообщения об ошибке валидации
2) Кнопка активируется только после успешной валидации формы

2020-10-10 23:09 UTC, alexstrive requested changes

2020-10-10 23:09 UTC, alexstrive commented on package.json
> +    "yarn": "^1.22.10"
Это лишнее

2020-10-10 23:09 UTC, alexstrive commented on src/helpers.ts
> +  if (email === undefined) return false
Можно использовать более простую конструкцию: 

```js
if (!email) {
  // code
}
```

2020-10-10 23:09 UTC, alexstrive commented on src/helpers.ts
> +  if (password === undefined) return false
То же самое, что и в предыдущем комментарии.

2020-10-10 23:09 UTC, alexstrive commented on src/screens/Auth/SignInScreen.tsx
> +    if (noErrors) {
Тут условный оператор и noErrors дублируют логику. Можно устанавливать значение состояние через напрямую. Например:

```js
setIsDisabledButton(noErrors)
```

И все же лучше идти от прямой логики и переименовать переменную в `hasErrors` (англ. Component has errors или Component contains errors). Но учти, что тогда нужно инвертировать логику выражения. По мере необходимости использовать `!hasErrors`. Легче воспринимается чем, `!noErrors`.

2020-10-10 23:09 UTC, alexstrive commented on src/screens/Auth/SignInScreen.tsx
> +  const [isDisabledButton, setIsDisabledButton] = useState(false)
Переименуй в `isButtonDisabled`, потому что сейчас из именования складывается ощущение, что disabled - это часть названия кнопки (как будто ты пишешь стиль для неё), а не состояние. 

Или лучше переименовать на то, что за что она отвечает: `isSignInDisabled`.

2020-10-10 23:09 UTC, alexstrive commented on src/screens/Auth/SignInScreen.tsx
> +        onPress={() => Linking.openURL('https://vk.com/asuhovitskiy')}
Андрей оценил 😉

2020-10-10 23:09 UTC, alexstrive commented on src/screens/Auth/SignUpScreen.tsx
> +    if (noErrors) {
Аналогичная история

2020-10-10 23:09 UTC, alexstrive commented on src/screens/Auth/SignUpScreen.tsx
> +  const [isDisabledButton, setIsDisabledButton] = useState(false)
Аналогично

2020-10-10 23:09 UTC, alexstrive commented on src/screens/Auth/SignUpScreen.tsx
> +function RegistrationScreen(): ReactElement {
Название файла и компонента разнятся.

2020-10-10 23:10 UTC, alexstrive commented
@gohabereg @Bukilan рассмотрите использование react-hook-form в дальнейшем для обработки ввода пользователя.

2020-10-10 23:13 UTC, alexstrive commented
@devchep @psychoreaper в принципе хорошая работа - исправите пару вещей и готов буду ставить одобрение.

2020-10-11 07:16 UTC, alexstrive reviewed
@devchep спасибо! Осталось только Merge конфликт разрешить. Я так понял это из за него не проходят проверки. @gohabereg @Bukilan смогли бы помочь?

2020-10-12 16:03 UTC, Bukilan approved these changes

2020-10-12 16:07 UTC, alexstrive approved these changes

2020-10-13 14:02 UTC, gohabereg approved these changes

2020-10-15 13:46 UTC, merged