create ui atom-card-result-value
microservices-course-itmo/frontend pull request #20
Opened 2020-10-11 21:43 UTC by borwi4ok

2020-10-13 08:51 UTC, alexstrive requested changes

2020-10-13 08:51 UTC, alexstrive commented on src/atoms/advice/index.tsx
> +      <Text>{displayData}</Text>
Я про это уже писал в другом PR. Глянь предыдущий PR.

2020-10-13 08:51 UTC, alexstrive commented on src/atoms/resultValue/index.tsx
> +        <Text style={styles.discount}>{` -${corDiscount}%`}</Text>
Можно упростить `<Text>' -{corDiscount}%'</Text>`

2020-10-13 08:51 UTC, alexstrive commented on src/atoms/resultValue/index.tsx
> +  const corDiscount = correctValueHandler(discount)
Не до конца понятно, что такое `corDiscount`. Предлагаю использовать полное имя.

2020-10-20 11:09 UTC, borwi4ok commented on src/atoms/advice/index.tsx
> +      <Text>{displayData}</Text>
видимо пр закрыли предыдущий,что именно нужно поменять?

2020-10-20 11:10 UTC, borwi4ok commented on src/atoms/resultValue/index.tsx
> +        <Text style={styles.discount}>{` -${corDiscount}%`}</Text>
так это же не будет тогда переменной

2020-10-20 23:24 UTC, alexstrive commented on src/atoms/resultValue/index.tsx
> +        <Text style={styles.discount}>{` -${corDiscount}%`}</Text>
Я кстати, допустил ошибку в примере. Одинарные кавычки не нужны. 

Не до конца понял почему нельзя интерполировать значение прямиком в структуру. 

@gohabereg глянь пожалуйста, мб я ошибаюсь.

2020-10-20 23:26 UTC, alexstrive commented on src/atoms/advice/index.tsx
> +      <Text>{displayData}</Text>
Переместить формирование текста из переменной во внутрь компонента Text.

2020-10-21 05:19 UTC, borwi4ok commented on src/atoms/resultValue/index.tsx
> +        <Text style={styles.discount}>{` -${corDiscount}%`}</Text>
Нам нужен знак % вместе с текстом,поэтому без обратных ковычек не обойтись я думаю

2020-10-22 00:25 UTC, borwi4ok commented on src/atoms/resultValue/index.tsx
> +        <Text style={styles.discount}>{` -${corDiscount}%`}</Text>
u was right 
damn
bruh

2020-10-22 00:30 UTC, borwi4ok commented on src/atoms/resultValue/index.tsx
> +  const corDiscount = correctValueHandler(discount)
всё зафиксил

2020-10-22 09:17 UTC, gohabereg approved these changes

2020-10-25 19:36 UTC, alexstrive approved these changes

2020-10-26 15:36 UTC, merged