Recommended filter page
microservices-course-itmo/frontend pull request #24
Opened 2020-10-22 00:13 UTC by borwi4ok

2020-10-22 14:15 UTC, gohabereg requested changes

2020-10-22 14:15 UTC, gohabereg commented on src/molecules/filter/recommendedFilterPage/radioButton.tsx
> +interface IRadioButton {
```suggestion
interface RadioButtonProps {
```

2020-10-22 14:15 UTC, gohabereg commented on src/molecules/filter/recommendedFilterPage/radioButton.tsx
> +      {checked ? <View style={styles.checkedCircle} /> : <View />}
```suggestion
      {checked && <View style={styles.checkedCircle} />}
```

2020-10-22 14:15 UTC, gohabereg commented on src/atoms/advice/index.tsx
> +function rightBordersHandler(value: number): number {
У тебя что-то не так с гитом, эти изменения уже есть в проекте.
Лучше удали репу и склонируй заново, чтобы не из форка делать реквесты

2020-10-28 14:17 UTC, alexstrive commented
@borwi4ok что по прогрессу?

2020-10-29 14:33 UTC, borwi4ok commented
@alexstrive сегодня доделаю это уже с форка,а дальше перейду на ветку

2020-10-30 18:42 UTC, gohabereg approved these changes

2020-11-01 17:02 UTC, merged