add confirmation screen
microservices-course-itmo/frontend pull request #27
Opened 2020-10-25 19:08 UTC by psychoreaper

проблемы с TS и дизайном

2020-10-25 19:34 UTC, alexstrive commented
В коде используется функцию `isName` из модуля `helpers`. Однако данная функция не экспортируется. Она даже не объявлена https://github.com/microservices-course-itmo/wineup-expo/blob/ui-team-5-confirm/src/helpers.ts 

Возможно забыли добавить в коммит.

2020-10-25 20:41 UTC, psychoreaper commented
Да, `isName` отвалился. Забыла добавить.

2020-10-26 12:39 UTC, alexstrive requested changes

2020-10-26 12:39 UTC, alexstrive commented on src/helpers.ts
> +export function isName(name: string): boolean | undefined {
А тут точно должно быть возвращаемое значение `undefined`? Всё же ожидать несколько типов возвращаемых значений не очень удобно с точки зрения использования этого кода другим разработчиком.

Обсуди это @Bukilan

2020-10-26 12:39 UTC, alexstrive commented on src/helpers.ts
> +  if (name.length === 0) return undefined
Если `undefined` будет убрано, то тут также его надо убрать.

2020-10-26 12:39 UTC, alexstrive commented on src/molecules/LabeledInput.tsx
> +      {isValid === false && (
```suggestion
      {!isValid && (
```

2020-10-26 12:51 UTC, Bukilan commented on src/helpers.ts
> +  if (name.length === 0) return undefined
Не надо возвращать undefined, это прям плохая практика. Даже название твоей функции подразумевает, что на вопрос ИМЯ_ЛИ ? должен вернуться ответ ДА/НЕТ, а не н̷̛̯̩̲̆̿͋͋̕и̷̨͔͙̠͖͑̋̽͠ч̵̦̞̳̒͘т̷̻̺͌ӧ̶̱͎́̔. Длинну строки можно проверить вообще перед вызовом функции, тогда не придется этих костылей городить.

2020-10-26 12:51 UTC, psychoreaper commented on src/molecules/LabeledInput.tsx
> +      {isValid === false && (
самое время сказать, что эта функция не моя, я пуллила её из другого места. скорее всего это вопрос к @devchep либо @Denidron

2020-10-26 12:52 UTC, alexstrive commented on src/molecules/LabeledInput.tsx
> +      {isValid === false && (
@devchep и @Denidron вопрос к вам ;)

2020-10-26 13:05 UTC, Bukilan reviewed
Поправь это все плез

2020-10-26 13:05 UTC, Bukilan commented on src/helpers.ts
> +  if (name.length === 0) return undefined
Не надо возвращать undefined, это прям плохая практика. Даже название твоей функции подразумевает, что на вопрос ИМЯ_ЛИ ? должен вернуться ответ ДА/НЕТ, а не н̷̛̯̩̲̆̿͋͋̕и̷̨͔͙̠͖͑̋̽͠ч̵̦̞̳̒͘т̷̻̺͌ӧ̶̱͎́̔. Длинну строки можно проверить вообще перед вызовом функции, тогда не придется этих костылей городить.

2020-10-26 13:05 UTC, Bukilan commented on src/helpers.ts
> +  return name.search(nameRegexp) === 0
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test

Есть метод у регулярок, который сам тестирует строку и возвращает ответ ДА/НЕТ

2020-10-26 13:05 UTC, Bukilan commented on src/helpers.ts
> +export function isCode(code: string): boolean {
Это что-то жуткое. Зачем вообще нужна эта функция ?

2020-10-26 13:05 UTC, Bukilan commented on src/helpers.ts
> +  if (code.length < 6) return true
Почему если код не совпадает по символам, то возвращается true ?

2020-10-26 13:05 UTC, Bukilan commented on src/helpers.ts
> +  return phone.search(phoneRegexp) === 0
regexObj.test(str)

2020-10-26 13:05 UTC, Bukilan commented on src/molecules/LabeledInput.tsx
> +      {isValid === false && (
isValid само по себе булевое значение. Ты тут сравниваешь `false === false`
Хватит `{isValid && ( ...`

2020-10-26 13:05 UTC, Bukilan commented on src/screens/Auth/ConfirmationScreen.tsx
> +  const timeToResend = 60
Константы, которые не меняются и не являются состоянием, выносим за функцию. Перенеси ее между импортами и функцией. 
Обусловлено тем, что при перерендере эта константа будет пересоздаваться, при условии что всегда будет одна и та же )

2020-10-26 13:05 UTC, Bukilan commented on src/helpers.ts
> +  if (!code) return true
Опять если нет кода возвращаем true ???? 
Тоже прикол. Я рассказывал, что если числу или строке сделать `!!code` то произойдет магия и вернется булево значение

2020-10-26 13:05 UTC, Bukilan commented on src/screens/Auth/ConfirmationScreen.tsx
> +        style={[
Атата, инлайн стили. Выносим в стили через style

2020-10-26 13:05 UTC, Bukilan commented on src/screens/Auth/SignUpScreen.tsx
> +  const isValidName = isName(userName)
Ты уверена, что если userName поменяется, то isValidName изменится ? Это же константа, а не состояние

2020-10-26 14:21 UTC, devchep commented on src/screens/Auth/SignUpScreen.tsx
> +  const isValidName = isName(userName)
@Bukilan Да, все ок, userName замыкается на isValidName и при каждом обращении значение берется текущее

2020-10-26 15:10 UTC, Bukilan commented on src/screens/Auth/SignUpScreen.tsx
> +  const isValidName = isName(userName)
Да, справедливо, я чет уже перегрелся )

2020-11-04 19:02 UTC, Bukilan approved these changes

2020-11-04 20:13 UTC, alexstrive approved these changes
@gohabereg глянь, что произошло с твоим кодом. Потому что я заметил, что там есть изменений с styled-components.

2020-11-04 20:19 UTC, alexstrive requested changes
Похоже, что мердж произошёл не с той веткой.

2020-11-05 10:09 UTC, gohabereg requested changes
1. Нужно удалить yarn-error.log (можно добавить в .gitignore)
2. Нужно удалить package-json.lock и юзать yarn в качестве пакетного менеджера

2020-12-01 10:01 UTC, closed without merging