add regexp validation helpers
microservices-course-itmo/frontend pull request #5
Opened 2020-09-25 14:03 UTC by psychoreaper

https://trello.com/c/dyZlX3EI/7-валидация-хэлепры

2020-09-25 16:01 UTC, gohabereg requested changes

2020-09-25 16:01 UTC, gohabereg commented on src/Helpers.js
> +// no cyrillic letters allowed
@Bukilan а вы договаривались писать на js?
Я предлагаю все же везде использовать ts

2020-09-25 16:01 UTC, gohabereg commented on src/Helpers.js
> +  return string.search(cyrillic) === -1;
Добавляйте плз пустые строки перед return
```suggestion

  return string.search(cyrillic) === -1;
```

2020-09-25 16:01 UTC, gohabereg commented on src/Helpers.js
> +  return email.search(emailRegexp) === 0 && latinCheck(email);
```suggestion

  return email.search(emailRegexp) === 0 && latinCheck(email);
```

2020-09-25 16:01 UTC, gohabereg commented on src/Helpers.js
> +  return password.search(passwordRegexp) === 0;
```suggestion

  return password.search(passwordRegexp) === 0;
```

2020-09-25 16:01 UTC, gohabereg commented on src/Helpers.js
> +// parts of email are separated with @ sign
Комменты лучше оформлять по JSDoc

2020-09-26 10:27 UTC, Bukilan commented on src/Helpers.js
> +// no cyrillic letters allowed
Нет, я как-то забыл совсем об этом ) @psychoreaper Получается нужно проставить типы для аргументов функции и для return

2020-09-27 19:38 UTC, gohabereg requested changes
Названия методов — лишь предложения, можно другие. Главное, чтобы имя отвечало на вопрос "что делает эта функция?" или в случае проверок было вопросом вроде "чем является аргумент?"/"какие свойства у аргумента?"

2020-09-27 19:38 UTC, gohabereg commented on src/Helpers.ts
> +  }
Кажется, что-то случилось с отступами

2020-09-27 19:38 UTC, gohabereg commented on src/Helpers.ts
> +// no cyrillic letters allowed
Все еще не по JSDoc — https://jsdoc.app/

2020-09-27 19:38 UTC, gohabereg commented on src/Helpers.ts
> +// no cyrillic letters allowed
```suggestion
/**
 * Returns true if string doesn't contain cyrillic chars
 *
 * @param string - string to check
 */
```

Для остальных методов аналогично

2020-09-27 19:38 UTC, gohabereg commented on src/Helpers.ts
> +function latinCheck(string: string): boolean {
Функции лучше называть с глаголов. 
```suggestion
function containsCyrillic(string: string): boolean {
```

2020-09-27 19:38 UTC, gohabereg commented on src/Helpers.ts
> +  export function emailCheck(email: string): boolean {
Или, если функция что-то проверяет, можно называть в формате `is<What>`?
```suggestion
  export function isEmail(email: string): boolean {
```

2020-09-27 19:38 UTC, gohabereg commented on src/Helpers.ts
> +  export function passwordCheck(password: string): boolean {
```suggestion
  export function isAllowedPassword(password: string): boolean {
```

2020-09-28 14:34 UTC, gohabereg submitted a review, later dismissed
По коду нет вопросов, нужно починить ESLint

2020-09-28 18:28 UTC, Bukilan submitted a review, later dismissed

2020-09-28 20:05 UTC, gohabereg commented
@Baulore @psychoreaper 
Поправил линтер. Опять же, он не просто так ругался — был ненужный escape character. Ошибки линтера можно смотреть тут на гитхабе, или запустив `yarn lint` в директории проекта. Если запустить `yarn lint --fix`, то он автоматом пофиксит то, что умеет фиксить.

@Bukilan надо еще раз поставить аппрув и можно мерджить

2020-09-28 20:05 UTC, gohabereg approved these changes

2020-09-29 17:40 UTC, Bukilan approved these changes

2020-10-01 16:42 UTC, merged