Profile first screen
microservices-course-itmo/frontend pull request #56
Opened 2021-02-15 19:02 UTC by Maximus135

This is not a finished pull request.

2021-02-15 19:29 UTC, gohabereg requested changes

2021-02-15 19:29 UTC, gohabereg commented on src/screens/UnauthorizedProfile.tsx
> +const StyledView = styled.View`
Все styled переменные лучше перенести под код компонента, так удобнее

2021-02-15 19:29 UTC, gohabereg commented on src/screens/UnauthorizedProfile.tsx
> +const styles = StyleSheet.create({
Не очень понял зачем мешать styled-components и StyleSheet, по идее все эти правила можно в styled-component перенести просто

2021-02-15 19:29 UTC, gohabereg commented on src/screens/UnauthorizedProfile.tsx
> +        <View>
Это кажется лишний контейнер

2021-02-15 19:29 UTC, gohabereg commented on src/screens/UnauthorizedProfile.tsx
> +const StyledView = styled.View`
Имеет смысл называть styled компоненты более осмысленно, типа `Container`, `ButtonLabel` и тд

2021-02-15 19:29 UTC, gohabereg commented on .eslintrc.json
> +    // "linebreak-style": ["error", "windows"],
Можно выпилить вообще эту строчку

2021-02-15 20:01 UTC, Maximus135 commented on src/screens/UnauthorizedProfile.tsx
> +        <View>
убрал

2021-02-15 20:02 UTC, Maximus135 commented on .eslintrc.json
> +    // "linebreak-style": ["error", "windows"],
выпилил

2021-02-15 20:03 UTC, Maximus135 commented on src/screens/UnauthorizedProfile.tsx
> +const styles = StyleSheet.create({
Не нашел другой возможности накинуть box-shadow так-как react native не умеет так) Возможно, есть варианты как исправить

2021-02-15 20:22 UTC, Maximus135 commented
<Modal> блокирует все элементы и нет возможность переключатся между категориями. Пока не нашел решение данной проблемы.

2021-02-16 14:38 UTC, Maximus135 commented on src/screens/UnauthorizedProfile.tsx
> +const StyledView = styled.View`
поправил

2021-02-16 14:39 UTC, Maximus135 commented
> <Modal блокирует все элементы и нет возможность переключатся между категориями. Пока не нашел решение данной проблемы.

Исправлено

2021-02-16 14:45 UTC, gohabereg approved these changes

2021-02-17 12:51 UTC, Bukilan approved these changes

2021-02-18 09:42 UTC, merged