optimization handlers
microservices-course-itmo/frontend pull request #58
Opened 2021-02-24 10:04 UTC by CleanBread

Вынес анонимные функции в функциональные выражения, методы жц были все перед рендером

2021-02-24 19:15 UTC, gohabereg requested changes

2021-02-24 19:15 UTC, gohabereg commented on src/molecules/Auth/LabeledDropdown.tsx
> +  const DropDownPickerChange = (item: any) => handleChange(item.value)
Методы нужно с маленькой буквы

2021-02-25 12:04 UTC, Bukilan commented on src/molecules/Auth/LabeledDropdown.tsx
> +  const DropDownPickerChange = (item: any) => handleChange(item.value)
@devchep как поправишь  - я или Жора заапрувии

2021-02-25 15:06 UTC, CleanBread commented on src/molecules/Auth/LabeledDropdown.tsx
> +  const DropDownPickerChange = (item: any) => handleChange(item.value)
поправил

2021-02-25 15:07 UTC, gohabereg approved these changes

2021-02-25 15:22 UTC, Bukilan approved these changes

2021-02-25 15:29 UTC, merged