style fixes
microservices-course-itmo/frontend pull request #63
Opened 2021-02-25 17:04 UTC by Maximus135

replacing styles to styled.componet in /screens/Auth

2021-02-28 19:39 UTC, gohabereg commented on src/screens/Auth/SignInConfirm.tsx
> +  // we need to fix this logic in styles for removing this constants into the bottom
В styled компоненты можно передавать пропсы:

```
const StyledViewWarningContainer = styled.View<{opacity: number}>`
  ...
  opacity: ${({ opactiy }) => opacity};
`
```

И использовать соответственно
```
<StyledViewWarningContainer opacity={warningOpacity()} />
```

2021-02-28 19:39 UTC, gohabereg commented on src/screens/Auth/SignInConfirm.tsx
> +  const StyledViewWarningContainer = styled.View`
Имхо `Styled` в начале стоит добавлять только если не хочется по другому называть, например если есть компонент SignUpButton, то делать
```
const StyledSignUpButton = styled(SignUpButton)``
```

Если это просто какая-то вьюха, то можно называть `WarningContainer` без `StyledView`.

@Bukilan что думаешь?

2021-02-28 19:39 UTC, gohabereg commented on src/screens/Auth/SignInConfirm.tsx
> +  const StyledViewWarningContainer = styled.View`
Ну в смысле и так норм, просто названия оч длинные получаются и эта добавка смысловой нагрузки особо не несет, потому что и так понятно, что у нас все компоненты Styled, а то что это View понятно из Container (ну и в целом не так важно, View это или что-то другое, главное что контейнер — значит в него можно что-нибудь вставить)

2021-02-28 19:39 UTC, gohabereg commented on src/atoms/Placeholder/index.tsx
> +export default Placeholder
Тоже имхо, но экспор лучше все же оставить сразу под компонентом, потому что если вдруг юзаются какие-то хоки, то придется в самый конец файла мотать, чтобы это посмотреть.

То есть в идеале такая структура файла:

```
imports

interfaces

constants

Component

export

styled-components

```

2021-03-04 07:35 UTC, Maximus135 commented on src/atoms/Placeholder/index.tsx
> +export default Placeholder
поправил экспорты

2021-03-04 07:37 UTC, Maximus135 commented on src/screens/Auth/SignInConfirm.tsx
> +  const StyledViewWarningContainer = styled.View`
типа Styled в начале дает понять что компонента имеет стили и не является дефолтной) ну хз короч)

2021-03-04 13:22 UTC, Maximus135 commented on src/screens/Auth/SignInConfirm.tsx
> +  // we need to fix this logic in styles for removing this constants into the bottom
готово

2021-03-04 13:41 UTC, gohabereg requested changes

2021-03-04 13:41 UTC, gohabereg commented on src/App.tsx
> +  const [isAuth, setIsAuth] = useState(false)
Пока авторизация не готова, лучше оставить как было))

```suggestion
  const [isAuth, setIsAuth] = useState(true)
```

2021-03-04 13:41 UTC, gohabereg commented on src/screens/Auth/AgeConfirm.tsx
> +        onPress={() => {
А зачем ты убрал методы? Было же лучше

2021-03-04 13:41 UTC, gohabereg commented on src/screens/Auth/AgeDenied.tsx
> +    <StyledBackButton activeOpacity={0.8} onPress={() => navigation.goBack()}>
И тут

2021-03-04 14:48 UTC, Maximus135 commented on src/screens/Auth/AgeConfirm.tsx
> +        onPress={() => {
поправил

2021-03-04 14:48 UTC, Maximus135 commented on src/screens/Auth/AgeDenied.tsx
> +    <StyledBackButton activeOpacity={0.8} onPress={() => navigation.goBack()}>
поправил

2021-03-04 14:49 UTC, Maximus135 commented on src/App.tsx
> +  const [isAuth, setIsAuth] = useState(false)
поправил

2021-03-04 15:22 UTC, gohabereg approved these changes

2021-03-04 15:37 UTC, Bukilan approved these changes

2021-03-04 15:41 UTC, merged