add registration component
microservices-course-itmo/frontend pull request #7
Opened 2020-09-25 22:15 UTC by devchep

Added registration component and styles for it
Added expo-font

2020-09-26 08:12 UTC, gohabereg requested changes

2020-09-26 08:12 UTC, gohabereg commented on src/screens/Registration.tsx
> +const styles = StyleSheet.create({
Предлагаю стили переносить в конец файла, чтобы при открытии сразу был виден компонент

2020-09-26 08:12 UTC, gohabereg commented on src/screens/Registration.tsx
> +  const userRegister = () => {
Имена функций стоит называть с глагола или по шаблону `on<Event>`, если это коллбэк.
В данном случае стоит или поменять местами слова — `registerUser`, или назвать просто `onSubmit`

2020-09-26 08:12 UTC, gohabereg commented on src/screens/Registration.tsx
> +      </View>
Вот это можно вынести в отдельный компонент (например `LabeledInput`) и переиспользовать его соответственно.
Но не знаю, насколько это сейчас оправданно, если потом будет библиотека компонентов

2020-09-26 13:37 UTC, devchep commented on src/screens/Registration.tsx
> +      </View>
Выделил компонент LabeledInput, можно вынести и переиспользовать в компоненте входа

2020-09-26 13:59 UTC, devchep commented on src/screens/Registration.tsx
> +const styles = StyleSheet.create({
Линтер ругался, надо добавить в .eslintrc.json
`"rules": {
    "no-use-before-define": "off",
    "@typescript-eslint/no-use-before-define": ["error", {"variables": false}]
  },`

2020-09-26 14:08 UTC, devchep commented on src/screens/Registration.tsx
> +const styles = StyleSheet.create({
Линтер ругался, надо тогда добавить в .eslintrc.json
`"rules": {
    "@typescript-eslint/no-use-before-define": ["error", {"variables": false,"functions": false, "classes": false}}]
  },`

2020-09-26 14:08 UTC, devchep commented on src/screens/Registration.tsx
> +const styles = StyleSheet.create({
"rules": { "@typescript-eslint/no-use-before-define": ["error", {"variables": false,"functions": false, "classes": false}] },

2020-09-26 14:09 UTC, devchep commented on src/screens/Registration.tsx
> +const styles = StyleSheet.create({
Линтер ругался, надо тогда добавить в .eslintrc.json
`"rules": { "@typescript-eslint/no-use-before-define": ["error", {"variables": false,"functions": false, "classes": false}}] },`

2020-09-26 14:13 UTC, devchep commented on src/screens/Registration.tsx
> +const styles = StyleSheet.create({
Линтер ругался, надо тогда добавить в .eslintrc.json
`"rules": {
    "@typescript-eslint/no-use-before-define":
    ["error", {"variables": false,"functions": false, "classes": false}]
  },`

2020-09-27 19:30 UTC, gohabereg requested changes
Готов ставить аппрув после фикса последних комментов

2020-09-27 19:30 UTC, gohabereg commented on src/screens/Registration.tsx
> +  setInputState: React.Dispatch<React.SetStateAction<string>>
Лучше придерживаться стандартных названий. В данном случае это будет `onChangeText` или просто `onChange`

2020-09-27 19:30 UTC, gohabereg commented on src/screens/Registration.tsx
> +const LabeledInput: React.FC<LabeledInputProps> = (
Давайте придерживаться правила один файл — один компонент.
В идеале конечно придерживаться atomic design, но это нам надо обсудить еще с @Bukilan и @alexstrive

2020-09-27 19:30 UTC, gohabereg commented on src/screens/Registration.tsx
> +  Props: LabeledInputProps
```suggestion
  props: LabeledInputProps
```

2020-09-28 18:29 UTC, Bukilan submitted a review, later dismissed

2020-09-29 12:32 UTC, devchep commented
Только сейчас увидел, что LabeledInput уже выделен в pr/9
Этот пр был открыт из форка(придется сделать новый?), сейчас уже есть доступ, в след раз буду пушить напрямую

2020-09-29 15:43 UTC, closed without merging