added .env and hide secret info
microservices-course-itmo/frontend pull request #73
Opened 2021-03-11 16:18 UTC by izukovdariy

2021-03-11 16:48 UTC, gohabereg requested changes

2021-03-11 16:48 UTC, gohabereg commented on .env
> +# Application environment variables.
Этот файл надо в игнор

2021-03-15 17:24 UTC, jojudre commented on .env
> +# Application environment variables.
да я сначала добавила, а потом подумала, как тогда вы возьмете данные из этого файла

2021-03-15 18:22 UTC, gohabereg commented on .env
> +# Application environment variables.
Можно сделать файл .env.sample, где указать только имена переменных без значений

2021-03-17 19:27 UTC, gohabereg approved these changes

2021-03-25 15:05 UTC, merged